"""浅色主题构建器"""

from src.panel.canvas.theme.tokens import CanvasTheme
from src.panel.canvas.theme.font_detection import build_font_kwargs


def build_light_theme(family: str, mono: str, sf) -> CanvasTheme:
    """VS Code Light+ / Notion inspired 浅色主题"""
    return CanvasTheme(
        bg_primary="#ffffff",
        bg_secondary="#f3f3f3",
        bg_surface="#e8e8e8",
        bg_surface_hover="#d4d4d4",
        bg_surface_dark="#dcdcdc",
        bg_overlay="#c0c0c0",
        text_primary="#1e1e1e",
        text_secondary="#555555",
        text_muted="#777777",
        text_on_accent="#ffffff",
        text_on_accent_bright="#1e1e1e",
        accent_blue="#0078d4",
        accent_blue_dim="#005a9e",
        accent_green="#0a8a6a",
        accent_green_dim="#006045",
        accent_red="#d32f2f",
        accent_red_dim="#b71c1c",
        accent_orange="#d48a1a",
        accent_orange_dim="#9a5a00",
        accent_mauve="#8b3a9e",
        accent_mauve_dim="#5c1a6e",
        accent_gray="#757575",
        accent_gray_dim="#5c5c5c",
        accent_teal="#00897b",
        accent_yellow="#b8860b",
        accent_pink="#ad1457",
        accent_warning="#d48a1a",
        accent_info="#0078d4",
        border_default="#d4d4d4",
        border_selected="#0078d4",
        border_hover="#1a8ce8",
        port_in_fill="#1e1e1e",
        port_in_outline="#0078d4",
        port_out_outline="#c0c0c0",
        shadow_color="#d0d0d0",
        grid_dot="#e0e0e0",
        grid_dot_sub="#ebebeb",
        grid_line="#e0e0e0",
        selection_box="#0078d4",
        selection_box_stipple="gray12",
        region_dim_color="#000000",
        region_dim_stipple="gray50",
        minimap_bg="#f3f3f3",
        minimap_bg_panel="#e0e0e0",
        minimap_viewport="#0078d4",
        minimap_viewport_shadow="#c0c0c0",
        minimap_border="#b0b0b0",
        minimap_edge="#c0c0c0",
        minimap_node_body="#d4d4d4",
        edge_default="#0078d4",
        edge_true="#0a8a6a",
        edge_false="#d32f2f",
        edge_loop="#0a8a6a",
        edge_timeout="#b8860b",
        edge_exit="#00897b",
        edge_source_handle="#b0b0b0",
        edge_target_handle="#3c3c3c",
        status_running="#0a8a6a",
        status_success="#0a8a6a",
        status_paused="#b8860b",
        status_error="#d32f2f",
        status_ready="#8a8a8a",
        toolbar_bg="#f3f3f3",
        panel_bg="#ffffff",
        panel_header_bg="#f3f3f3",
        toolbar_secondary_bg="#e8e8e8",
        panel_accent_border="#0078d4",
        page_bg="#ffffff",
        card_bg="#f5f5f5",
        dialog_bg="#ffffff",
        input_bg="#fafafa",
        input_fg="#1e1e1e",
        separator_color="#e0e0e0",
        success_color="#0a8a6a",
        warning_color="#b8860b",
        danger_color="#d32f2f",
        btn_bg="#d8d8d8",
        btn_bg_hover="#cccccc",
        btn_border="#b0b0b0",
        btn_disabled_bg="#eaeaea",
        btn_disabled_fg="#b0b0b0",
        row_stripe_bg="#f5f5f5",
        border_strong="#a0a0a0",
        zone_border="#c0c0c0",
        breadcrumb_bg="#e8e8e8",
        empty_state_icon="#aaaaaa",
        hover_highlight="#e0e0e0",
        **build_font_kwargs(family, mono, sf),
    )
